services:
  web-bimbel-dev:
    image: web-bimbel:latest
    build: .
    container_name: web-bimbel-dev
    restart: always
    ports:
      - "2002:80"
    networks:
      - web-bimbel-net

networks:
  web-bimbel-net:
    driver: bridge
