version: "3.8"

services:
  web-bimbel:
    image: web-bimbel:latest
    container_name: web-bimbel
    restart: always
    ports:
      - "2000:80"
    networks:
      - leskomputer-net
    environment:
      - VIRTUAL_HOST=leskomputer.akr.co.id
      - VIRTUAL_PORT=80

networks:
  leskomputer-net:
    driver: bridge
