version: "3.8"

services:
  web-bimbel-dev:
    image: web-bimbel-dev:latest
    container_name: web-bimbel-dev
    restart: always
    ports:
      - "2001:80"
    networks:
      - leskomputer-net
    environment:
      - VIRTUAL_HOST=leskomputer.akr.co.id
      - VIRTUAL_PORT=80

networks:
  leskomputer-net:
    driver: bridge
